name: digital_signature
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  syncfusion_flutter_pdf: ^20.3.57
  syncfusion_flutter_signaturepad: ^20.3.57
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  syncfusion_flutter_pdfviewer: ^20.3.57
  nil: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/certificate/certificate.pfx
    - assets/pdf/sample.pdf
